### ISSUE TITLE
[NO ISSUE] Just a question

### ISSUE THREAD

**Issue by deknarf** [xklusive/laravel-battlenet-api#10]
I have no idea how to contact you, so I will use this method of conversation.

Hello,

As a novice, I have a novice question: To get this working, would I need to have the laravel library installed on my server, prior to following the (composing & publishing) install steps? I use an installer within cPanel to install laravel for me.

`EDIT: This is my fresh laravel install https://100ivclub.com/hg/`
Can I work from that?... pretty confusing ^^

Sorry if I posted this in the wrong section.

Regards,
Frank

**Comment by atraides** [comment]
Sure, don't worry. You could use this laravel with the library for sure.

However it depending on which version of laravel you are using you may need to wait a little. The latest version of Laravel 5.5 is not supported yet. I am currently working on to make that happen.

I will also create a wiki with a bit more details how to install and use this.

Kind Regards,
Daniel

**Comment by deknarf** [comment]
Ah, that explains my error :)

```
ivclub@www73 [~/public_html/hg]# composer require xklusive/laravel-battlenet-api                                             Using version ^0.9.1 for xklusive/laravel-battlenet-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package xklusive/laravel-battlenet-api No version set (parsed as 1.0.0) is satisfiable by xklusive/laravel-battlenet-api[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for xklusive/laravel-battlenet-api ^0.9.1 -> satisfiable by xklusive/laravel-battlenet-api[0.9.1].
    - xklusive/laravel-battlenet-api 0.9.1 requires laravel/framework ~5.3.0 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

```

**Comment by atraides** [comment]
Yes exactly. The current version on github supports Laravel 5.5 but I need to create a release for it so packagist.org will pick it up as well. 

I want to iron out a few things first, but I think later today I will push version 1.0 to packigist.

**Comment by atraides** [comment]
I pushed v1.0 to pacakgist, You should be able to include it now. I will create a wiki about the installation tomorrow,
