### ISSUE TITLE
configuration not read with laravel 5.5

### ISSUE THREAD

**Issue by olamatson** [xklusive/laravel-battlenet-api#22]
Using Laravel 5.5.
Published configuration is not read. adding the filename to the tag helps
    private function getApiEndPoint()
    {
        return config('battlenet-api.battlenet-api.domain');
    }

**Comment by atraides** [comment]
Let me check it why this is the case.

**Comment by sdousley** [comment]
This is because the battlenet-api.php config file has a battlenet-api index in the array.  remove this index, and it works perfectly fine.

Link to my working battlenet-api.php file: https://gist.github.com/sdousley/af4aa0ee6a151c559345eb667dcba75d 

Masked my API key for obvious reasons

**Comment by olamatson** [comment]
Hi,

Cool, makes sense. Thanks!

Ola

**Comment by olamatson** [comment]
Didn't work, here is a bit of analysis. This is my findings for this specific issue. Happy to hear if somebody has more complete explanation
removing the tag, i.e. config/battlenet-api.php contains:
return [
// no tag here
[
'api_key' => 'the key',
'locale' => 'the locale',
'domain' => 'https://eu.api.battle.net',
'cache' => true, 
],
];
calling config('battlenet-api') will return an indexed array with 2 elements [0] being the default one in the 'vendor' directory and [1] will return my overrides in my config folder. So to get the value from my example from my initial post needs to be
config('battlenet-api')[1]['domain];
So, the your-config.php needs to be an associative array and thus contain tags for all entries. Original format is fine but querying the contents needs to contain the filename, i.e.
config('filenamewithoutextention.tag.tag');
config('battlenet-api.battlenet-api.domain');
filename needs to be in the request.

This is done in Laravel 5.5, php 7.2. Hope it helps

Ola

**Comment by sdousley** [comment]
Hi Ola

My apologies, I probably was a little unclear in what I said compared to what I meant!

It's not just a case of removing the array index tag, you need to remove the whole top level of the array in that file.

What you need (no comments) is:

return [
    'api_key' => 'the key',
    'locale'
....
];

This will allow you to access using config('battlenet-api.api_key') etc

**Comment by sdousley** [comment]
I've put up a pull request from my own fork of this to fix this

**Comment by olamatson** [comment]
That’s it. nice and clean!

Ola

**Comment by atraides** [comment]
I created a new release v1.0.1 with the fixes. 

Thanks for the help
