### ISSUE TITLE
Exceptions not rethrown

### ISSUE THREAD

**Issue by sdousley** [xklusive/laravel-battlenet-api#23]
I just tried: 

try {
    $x = $this->wowService->getCharacter($realm->getName(), $formData['Name']);
} catch (ClientException $e) {
    dd('ClientException');
} catch (\Exception $e) {
    dd('\Exception');
}
dd('here');

and when there is no character on the realm specified, I see the \GuzzleHttp\Exception\ClientException, however, I also then see the dd('here');

I had a look, and the reason is that the exception is caught within "protected function api()" (line 63 of BattlenetHttpClient.php, but is not thrown.

by simply changing the "return $e;" on line 98 to "throw $e;" this fixes the issue, and I then see dd('ClientException')

**Comment by sdousley** [comment]
I've put up a pull request for this for you.

**Comment by atraides** [comment]
I pushed a new release with the fix.

Thanks for your help.
