### ISSUE TITLE
Composer dependencies (Laravel 5.4/5.5 not supported)

### ISSUE THREAD

**Issue by Fjarnskaggl** [xklusive/laravel-battlenet-api#8]
Would it be possible to give the Laravel version requirement a bump? I'm not seeing any issue with bumping it to the latest stable build (5.5)

**Comment by xklusive** [comment]
Hello Fjarnskaggl,

Of course, i'll up the Laravel version requirement today or tomorrow :)

**Comment by Gillon** [comment]
Much appreciated, thank you :)

**Comment by sdousley** [comment]
Any update on this? I've had a look around, and this looks to be the best Battle.net API package around, other than the "requirement" for 5.3.  If it could get a bump to 5.5, that would be awesome.

**Comment by xklusive** [comment]
Hello

Thanks @atraides for your help on the project :)

**Comment by sdousley** [comment]
Ah, that's cool that it'll be done "properly" rather than just bodged to work :) Looking forward to a proper release.

**Comment by atraides** [comment]
I might need to disable or rework the mount list function for a release because data provided by Blizz looks like incomplete: https://us.battle.net/forums/en/bnet/topic/20759527665

Do you have the same issue or is this just for me?

**Comment by atraides** [comment]
I pushed an update to the code to packagist. v1.0 should be fine with Laravel 5.5. I still need to create a backward compatible version for Laravel 5.4 as the last PHP5 version.

If you have any issues with the release please let me know.
